config/routes.rb
Laufverwaltung::Application.routes.draw do
  resources :shoes
  put "shoes/:id/hide" => "shoes#hide", as: 'hide_shoe'
  put "shoes" => "shoes#unhide", as: 'unhide_shoes'
	root to: 'pages#home'
	get "runs/statistic" => "runs#statistic", as: 'statistic'

  resources :runs
	resources :users, only: [:new, :create]

  post "runs/output" =>"runs#output", as: 'output'

	get "login" => "sessions#new", as: 'login'
	post "sessions" => "sessions#create", as: 'sessions'
	delete "logout" => "sessions#destroy", as: 'logout'

	get "pages/about" => "pages#about", as: 'about'
	get "pages/contact" => "pages#contact", as: 'contact'

end

app/models/run.rb
class Run < ActiveRecord::Base
before_validation :remove_comma

	belongs_to :user
	belongs_to :shoe

  validates :distance, numericality: {:greater_than => 0, :less_than => 200}
  validates :run_hours, numericality: {:only_integer => true, :greater_than_or_equal_to => 0, :less_than => 24}
  validates :run_minutes, numericality: {:only_integer => true, :greater_than_or_equal_to => 0, :less_than => 60}
  validates :run_seconds, numericality: {:only_integer => true, :greater_than_or_equal_to => 0, :less_than => 60}

	scope :nutzer, lambda {|current_user| where(:user_id => current_user)}
	scope :zeitraum, lambda {|startdatum, enddatum| where(:run_at => (startdatum)..(enddatum))}
	scope :schuhmarke, lambda {|schuh| where(:shoe_id => schuh)}
  scope :sichtbar, where(:viewable => true)
  scope :unsichtbar, where(:viewable => false)
	#scope :summe, sum(:distance) funktioniert nicht ! siehe unten, deswegen wird sie im Controller angehängt
	#def self.summe
	# sum('distance')
	#end
	#scope :summe, sum('distance') Scope-compatible methods return a scoped object, not a number as is the case with sum. 
	#You need to use this approach with things that return a final value that can't be scoped further.
	#http://stackoverflow.com/questions/7366193/why-does-using-sum-in-a-rails-3-1-scope-result-in-an-error


	def remove_comma
		@attributes["distance"].gsub!(',', '.') if attribute_present?("distance")
	end

end

app/controllers/runs_controller.rb
# encoding: utf-8
class RunsController < ApplicationController

	before_filter :require_login
  # GET /runs
  # GET /runs.json


	def statistic
		#Gesamtdistanz		
		@summe_distance_all = Run.nutzer(current_user.id).sum(:distance)
		startdatum = '2011-01-01'.to_date
		enddatum = '2011-12-31'.to_date
		#Distanz 2011
		@summe_distance_2011 = Run.nutzer(current_user.id).zeitraum(startdatum, enddatum).sum(:distance)
		startdatum = '2012-01-01'.to_date
		enddatum = '2012-12-31'.to_date
		#Distanz 2012
		@summe_distance_2012 = Run.nutzer(current_user.id).zeitraum(startdatum, enddatum).sum(:distance)
		@JAN_2011 = Run.nutzer(current_user.id).zeitraum('2011-01-01'.to_date, '2011-01-31'.to_date).sum(:distance)
		@FEB_2011 = Run.nutzer(current_user.id).zeitraum('2011-02-01'.to_date, '2011-02-28'.to_date).sum(:distance)
		@MAR_2011 = Run.nutzer(current_user.id).zeitraum('2011-03-01'.to_date, '2011-03-31'.to_date).sum(:distance)
		@APR_2011 = Run.nutzer(current_user.id).zeitraum('2011-04-01'.to_date, '2011-04-30'.to_date).sum(:distance)
		@MAY_2011 = Run.nutzer(current_user.id).zeitraum('2011-05-01'.to_date, '2011-05-31'.to_date).sum(:distance)
		@JUN_2011 = Run.nutzer(current_user.id).zeitraum('2011-06-01'.to_date, '2011-06-30'.to_date).sum(:distance)
		@JUL_2011 = Run.nutzer(current_user.id).zeitraum('2011-07-01'.to_date, '2011-07-31'.to_date).sum(:distance)
		@AUG_2011 = Run.nutzer(current_user.id).zeitraum('2011-08-01'.to_date, '2011-08-31'.to_date).sum(:distance)
		@SEP_2011 = Run.nutzer(current_user.id).zeitraum('2011-09-01'.to_date, '2011-09-30'.to_date).sum(:distance)
		@OCT_2011 = Run.nutzer(current_user.id).zeitraum('2011-10-01'.to_date, '2011-10-31'.to_date).sum(:distance)
		@NOV_2011 = Run.nutzer(current_user.id).zeitraum('2011-11-01'.to_date, '2011-11-30'.to_date).sum(:distance)
		@DEC_2011 = Run.nutzer(current_user.id).zeitraum('2011-12-01'.to_date, '2011-12-31'.to_date).sum(:distance)
		@JAN_2012 = Run.nutzer(current_user.id).zeitraum('2012-01-01'.to_date, '2012-01-31'.to_date).sum(:distance)
		@FEB_2012 = Run.nutzer(current_user.id).zeitraum('2012-02-01'.to_date, '2012-02-28'.to_date).sum(:distance)
		@MAR_2012 = Run.nutzer(current_user.id).zeitraum('2012-03-01'.to_date, '2012-03-31'.to_date).sum(:distance)
		@APR_2012 = Run.nutzer(current_user.id).zeitraum('2012-04-01'.to_date, '2012-04-30'.to_date).sum(:distance)
		@MAY_2012 = Run.nutzer(current_user.id).zeitraum('2012-05-01'.to_date, '2012-05-31'.to_date).sum(:distance)
		@JUN_2012 = Run.nutzer(current_user.id).zeitraum('2012-06-01'.to_date, '2012-06-30'.to_date).sum(:distance)
		@JUL_2012 = Run.nutzer(current_user.id).zeitraum('2012-07-01'.to_date, '2012-07-31'.to_date).sum(:distance)
		@AUG_2012 = Run.nutzer(current_user.id).zeitraum('2012-08-01'.to_date, '2012-08-31'.to_date).sum(:distance)
		@SEP_2012 = Run.nutzer(current_user.id).zeitraum('2012-09-01'.to_date, '2012-09-30'.to_date).sum(:distance)
		@OCT_2012 = Run.nutzer(current_user.id).zeitraum('2012-10-01'.to_date, '2012-10-31'.to_date).sum(:distance)
		@NOV_2012 = Run.nutzer(current_user.id).zeitraum('2012-11-01'.to_date, '2012-11-30'.to_date).sum(:distance)
		@DEC_2012 = Run.nutzer(current_user.id).zeitraum('2012-12-01'.to_date, '2012-12-31'.to_date).sum(:distance)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @runs }
    end
	end

	def output
		startdatum = params[:startdatum].to_date
		enddatum = params[:enddatum].to_date
		respond_to do |format|
			if enddatum.nil? or startdatum.nil? or (startdatum > enddatum)
        format.html { redirect_to statistic_path, notice: 'Fehlerhaftes Datum'}
			else
 				@summe_distance_calc = Run.nutzer(current_user.id).zeitraum(startdatum, enddatum).sum(:distance)
      	format.html # output.html.erb
		  end
		end
	end

  def index
    @runs = current_user.runs.order( 'run_at DESC' )
		@nickname = current_user.nickname
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @runs }
    end
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
    @run = current_user.runs.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @run }
    end
  end

  # GET /runs/new
  # GET /runs/new.json
  def new
    @run = current_user.runs.build
		@schuhe_eines_nutzer = Shoe.nutzer(current_user.id)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @run }
    end
  end

  # GET /runs/1/edit
  def edit
    @run = current_user.runs.find(params[:id])
		@schuhe_eines_nutzer = Shoe.nutzer(current_user.id)
  end

  # POST /runs
  # POST /runs.json
  def create
    @run = current_user.runs.build(params[:run])
		# Errechne Gesamtzeit in Sekunden
		@run.runtime_in_seconds = (params[:run][:run_hours].to_i)*3600+(params[:run][:run_minutes].to_i)*60+(params[:run][:run_seconds].to_i)
    respond_to do |format|
      if @run.save
        format.html { redirect_to runs_path, notice: 'Lauf erfolgreich erstellt.' }
        format.json { render json: @run, status: :created, location: @run }
      else
        format.html { render action: "new" }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /runs/1
  # PUT /runs/1.json
  def update
    @run = current_user.runs.find(params[:id])
		# Errechne Gesamtzeit in Sekunden
		@run.runtime_in_seconds = (params[:run][:run_hours].to_i)*3600+(params[:run][:run_minutes].to_i)*60+(params[:run][:run_seconds].to_i)

		respond_to do |format|
      if @run.update_attributes(params[:run])
        format.html { redirect_to runs_path, notice: 'Lauf erfolgreich aktualisiert.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run = current_user.runs.find(params[:id])
    @run.destroy
    respond_to do |format|
      format.html { redirect_to runs_url }
      format.json { head :ok }
    end
  end

	def require_login
		unless user_signed_in?
			redirect_to login_path,
			alert: "Bitte zuerst anmelden"
		end
	end
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/runs/_form.html.erb
<%= form_for @run, :html => { :class => 'run_form'} do |f| %>
  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul>
      <% @run.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="label_text">
    <%= f.label :distance %><br />
    <%# f.text_field :distance %>
		<%= f.text_field :distance, :size => 6, :maxlength => 6, :value => (number_with_delimiter(f.object.distance, :separator => ',')) %>km
  </div>

	<div class="label_text">
    <%= f.label :run_hours %><br />
    <%= f.text_field :run_hours, :size => 2,  :maxlength => 2 %>
  </div>
	<div class="label_text">
    <%= f.label :run_minutes %><br />
    <%= f.text_field :run_minutes, :size => 2,  :maxlength => 2 %>
  </div>
	<div class="label_text">
    <%= f.label :run_seconds %><br />
    <%= f.text_field :run_seconds, :size => 2,  :maxlength => 2 %>
  </div>

	<div class="label_text">
    <%= f.label :fullname %><br />
		<%= f.collection_select :shoe_id, @schuhe_eines_nutzer, :id, :fullname, prompt: "Bitte wählen" %>
  </div>

	<div class="label_text">
    <%= f.label :run_at %><br />
		<%= f.date_select :run_at, :end_year => Time.now.year, :start_year => Time.now.year- 3 %>
  </div>

	<div>
    <%= f.submit %>
  </div>
<% end %>

app/views/runs/_laufstatistik.erb
	<h3>Laufstatistik</h3>

	<div class="block_1">
		<p>Gesamtdistanz: <%= number_with_precision(@summe_distance_all) %> km</p>
	</div>

	<div class="block_1">
		<p>Oder wähle einen Zeitraum</p>
		<%= form_tag output_path do %>
			<div class="field">
				<%= label_tag(:startdatum, "Start") %>
				<%= text_field_tag :startdatum, nil, :size => 10, :maxlength => 10 %>
			</div>	

			<div class="field">
				<%= label_tag(:enddatum, "Ende") %>
				<%= text_field_tag :enddatum, nil, :size => 10, :maxlength => 10 %>
			</div>	

			<div class="actions">
				<%= submit_tag("Zeige Kilometerleistung") %>
			</div>	

		<% end %>
	</div>

<table class="bordertable narrow">
<thead>
  <tr>
    <th>Monat</th>
    <th>2011</th>
    <th>2012</th>
  </tr>
</thead>
<tfoot>
  <tr>
    <td>Summe</td>
    <td class="nowrap"><%= number_with_precision(@summe_distance_2011) %> km</td>
    <td class="nowrap"><%= number_with_precision(@summe_distance_2012) %> km</td>
  </tr>
</tfoot>
<tbody>
  <tr>
    <td>Januar</td>
		<td class="nowrap"><%= number_with_precision @JAN_2011 %> km</td>
		<td class="nowrap"><%= number_with_precision @JAN_2012 %> km</td>
  </tr>
  <tr>
    <td>Februar</td>
		<td class="nowrap"><%= number_with_precision @FEB_2011 %> km</td>
		<td class="nowrap"><%= number_with_precision @FEB_2012 %> km</td>
  </tr>
  <tr>
		<td>März</td>
		<td class="nowrap"><%= number_with_precision @MAR_2011 %> km</td>
		<td class="nowrap"><%= number_with_precision @MAR_2012 %> km</td>
  </tr>
  <tr>
		<td>April</td>
		<td class="nowrap"><%= number_with_precision @APR_2011 %> km</td>
		<td class="nowrap"><%= number_with_precision @APR_2012 %> km</td>
  </tr>
  <tr>
		<td>Mai</td>
		<td class="nowrap"><%= number_with_precision @MAY_2011 %> km</td>
		<td class="nowrap"><%= number_with_precision @MAY_2012 %> km</td>
  </tr>
  <tr>
		<td>Juni</td>
		<td class="nowrap"><%= number_with_precision @JUN_2011 %> km</td>
		<td class="nowrap"><%= number_with_precision @JUN_2012 %> km</td>
  </tr>
  <tr>
		<td>Juli</td>
		<td class="nowrap"><%= number_with_precision @JUL_2011 %> km</td>
		<td class="nowrap"><%= number_with_precision @JUL_2012 %> km</td>
  </tr>
  <tr>
		<td>August</td>
		<td class="nowrap"><%= number_with_precision @AUG_2011 %> km</td>
		<td class="nowrap"><%= number_with_precision @AUG_2012 %> km</td>
  </tr>
  <tr>
		<td>September</td>
		<td class="nowrap"><%= number_with_precision @SEP_2011 %> km</td>
		<td class="nowrap"><%= number_with_precision @SEP_2012 %> km</td>
  </tr>
  <tr>
		<td>Oktober</td>
		<td class="nowrap"><%= number_with_precision @OCT_2011 %> km</td>
		<td class="nowrap"><%= number_with_precision @OCT_2012 %> km</td>
  </tr>
  <tr>
		<td>November</td>
		<td class="nowrap"><%= number_with_precision @NOV_2011 %> km</td>
		<td class="nowrap"><%= number_with_precision @NOV_2012 %> km</td>
  </tr>
  <tr>
		<td>Dezember</td>
		<td class="nowrap"><%= number_with_precision @DEC_2011 %> km</td>
		<td class="nowrap"><%= number_with_precision @DEC_2012 %> km</td>
  </tr>
</tbody>
</table>

app/views/runs/edit.html.erb
<% provide(:title, 'Letzte Läufe - Lauf bearbeiten') %>
<%= render partial: 'shared/navigation', locals: {nav_runs: 'active', nav_shoes: '', nav_statistic: '', nav_about: '', nav_contact: ''} %>
<h3>Lauf bearbeiten</h3>
<%= render 'form' %>
<%= link_to 'Zurück', runs_path, :class => "speziell" %>

app/views/runs/index.html.erb
<% provide(:title, 'Letzte Läufe') %>
<%= render partial: 'shared/navigation', locals: {nav_runs: 'active', nav_shoes: '', nav_statistic: '', nav_about: '', nav_contact: ''} %>
<h3>Die letzten Läufe von <%= @nickname %></h3>
	<table class="bordertable narrow">
		<thead>
			<tr>
				<th>Distanz</th>
				<th>Laufzeit</th>
				<th>Tempo</th>
				<th>Marke</th>
				<th>Model</th>
				<th class="nowrap">gelaufen am:</th>
				<th></th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @runs.each do |run| %>
				<tr>
					<td class="nowrap"><%= number_with_precision run.distance %> km</td>
					<td class="nowrap"><%= (Time.mktime(0)+(run.runtime_in_seconds)).strftime("%k:%M:%S") %></td>
					<td class="nowrap"><%= (Time.mktime(0)+((run.runtime_in_seconds) / (run.distance))).strftime("%M:%S") %> min/km</td>
					<td class="nowrap"><%= run.shoe.brand %></td>
					<td class="nowrap"><%= run.shoe.description %></td>
					<td class="nowrap"><%= localize run.run_at , form: :short %></td>
					<td class="nowrap"><%= link_to 'Bearbeiten', edit_run_path(run), :class => "normal" %></td>
					<td class="nowrap"><%= link_to 'Löschen', run, :class => "normal", confirm: 'Sind Sie sicher ?', method: :delete %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<p>
	<%= link_to 'Neuen Lauf eingeben', new_run_path, :class => "speziell" %> 
	</p>

app/views/runs/new.html.erb
<% provide(:title, 'Letzte Läufe - Neuen Lauf eingeben') %>
<%= render partial: 'shared/navigation', locals: {nav_runs: 'active', nav_shoes: '', nav_statistic: '', nav_about: '', nav_contact: ''} %>
<h3>Neuen Lauf eingeben</h3>
<%= render 'form' %>
<%= link_to 'Zurück', runs_path, :class=>"speziell" %>

app/views/runs/output.html.erb
<% provide(:title, 'Statistik') %>
<%= render partial: 'shared/navigation', locals: {nav_runs: '', nav_shoes: '', nav_statistic: 'active', nav_about: '', nav_contact: ''} %>
<h3>Ausgabe</h3>
<div>Errechnete Distanz ist <%= number_with_precision(@summe_distance_calc) %> km</div>
<%= link_to "Zurück zur Statistik", statistic_path, :class => "speziell" %>

app/views/runs/show.html.erb
<%= debug params %>
<p>
  <b>Distanz:</b>
  <%= number_with_precision @run.distance %>
</p>

<p>
  <b>Schuh:</b>
  <%= @run.shoe.brand %>
</p>

<%= link_to 'Bearbeiten', edit_run_path(@run) %> |
<%= link_to 'Liste', runs_path %>