config/routes.rb
Laufverwaltung::Application.routes.draw do
  resources :shoes
  put "shoes/:id/hide" => "shoes#hide", as: 'hide_shoe'
  put "shoes" => "shoes#unhide", as: 'unhide_shoes'
	root to: 'pages#home'
	get "runs/statistic" => "runs#statistic", as: 'statistic'

  resources :runs
	resources :users, only: [:new, :create]

  post "runs/output" =>"runs#output", as: 'output'

	get "login" => "sessions#new", as: 'login'
	post "sessions" => "sessions#create", as: 'sessions'
	delete "logout" => "sessions#destroy", as: 'logout'

	get "pages/about" => "pages#about", as: 'about'
	get "pages/contact" => "pages#contact", as: 'contact'

end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
	has_many :runs
	belongs_to :user
  validates :brand, :presence => true
  validates :description, :presence => true


	scope :nutzer, lambda {|current_user| where(:user_id => current_user)}
  scope :sichtbar, where(:viewable => true)
  scope :unsichtbar, where(:viewable => false)
end

app/controllers/shoes_controller.rb
# encoding: utf-8
class ShoesController < ApplicationController
	before_filter :require_login

  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = current_user.shoes.sichtbar
		@hide_shoes = current_user.shoes.unsichtbar.count
    respond_to do |format|
      format.html # index.html.erb
			format.js
      format.json { render json: @shoes }
    end
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
    @shoe = current_user.shoes.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shoe }
    end
  end

  # GET /shoes/new
  # GET /shoes/new.json
  def new
    @shoe = current_user.shoes.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shoe }
    end
  end

  # GET /shoes/1/edit
  def edit
    @shoe = current_user.shoes.find(params[:id])
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = current_user.shoes.build(params[:shoe])
		#Setze Namen zusammen, dieser wird in der Schuhverwaltung angezeigt
		@shoe.fullname = (params[:shoe][:brand].to_s)+(params[:shoe][:description].to_s)
    respond_to do |format|
      if @shoe.save
        format.html { redirect_to shoe_path, notice: 'Neuen Laufschuh erfolgreich erzeugt' }
        format.json { render json: @shoe, status: :created, location: @shoe }
      else
        format.html { render action: "new" }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

	#def hide:
	#Blendet einzelne Schuhe aus der Liste aus, löschen ist nicht sinnvoll,
	#da dann die Runs nicht konsistent sind, da "Schuh" Pflichfeld ist
	def hide
    @shoe = current_user.shoes.find(params[:id])
		@shoe.viewable = false
		@shoe.save
    respond_to do |format|
      format.html { redirect_to shoes_path }
		end
	end

	#def unhide:
	#Blendet alle ausgeblendeten Schuhe wieder ein
	def unhide
		@shoes = current_user.shoes.unsichtbar
		@shoes.each do |shoe|
			shoe.viewable=true
			shoe.save
		end
    respond_to do |format|
      format.html { redirect_to shoes_path }
		end
	end

  # PUT /shoes/1
  # PUT /shoes/1.json
  def update
    @shoe = current_user.shoes.find(params[:id])

    respond_to do |format|
      if @shoe.update_attributes(params[:shoe])
        format.html { redirect_to shoes_path, notice: 'Laufschuh erfolgreich geändert' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe = current_user.shoes.find(params[:id])
    @shoe.destroy

    respond_to do |format|
      format.html { redirect_to shoes_url }
      format.json { head :ok }
    end
  end

	def require_login
		unless user_signed_in?
			redirect_to login_path,
			alert: "Bitte zuerst anmelden"
		end
	end
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/shoes/_form.html.erb
<%= form_for @shoe, :html => { :class => 'shoe_form'}  do |f| %>
  <% if @shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% @shoe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="label_text">
    <%= f.label :brand %><br />
    <%= f.text_field :brand %>
  </div>
  <div class="label_text">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="label_text">
    <%= f.hidden_field :viewable, :value => 'true' %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/shoes/edit.html.erb
<% provide(:title, 'Schuhverwaltung - Schuh bearbeiten') %>
<%= render partial: 'shared/navigation', locals: {nav_runs: '', nav_shoes: 'active', nav_statistic: '', nav_about: '', nav_contact: ''} %>
<h3>Schuh bearbeiten</h3>
<%= render 'form' %>
<%= link_to 'Zurück', :back, :class => "speziell" %>

app/views/shoes/index.html.erb
<% provide(:title, 'Schuhverwaltung') %>
<%= render partial: 'shared/navigation', locals: {nav_runs: '', nav_shoes: 'active', nav_statistic: '', nav_about: '', nav_contact: ''} %>
	<h3>Schuhverwaltung</h3>
	<table class="bordertable narrow">
		<thead>
			<tr>
				<th>Hersteller</th>
				<th>Beschreibung</th>
				<th class="nowrap">gelaufene Distanz</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @shoes.each do |shoe| %>
				<tr>
					<td class="nowrap"><%= shoe.brand %></td>
					<td class="nowrap"><%= shoe.description %></td>
					<td class="nowrap"><%= number_with_precision(shoe.runs.sum(:distance)) %> km</td>
					<td class="nowrap"><%= link_to 'Bearbeiten', edit_shoe_path(shoe),:class => "normal" %></td>
					<td class="nowrap"><%= link_to 'Ausblenden', hide_shoe_path(shoe), method: :put, :class => "normal" %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<p><%= link_to 'Neuen Schuh eingeben', new_shoe_path, :class => "speziell" %> | <%= link_to 'Ausgeblendete Schuhe zeigen', unhide_shoes_path, :class => "speziell", method: :put %> (<%= @hide_shoes %>)</p>

app/views/shoes/new.html.erb
<% provide(:title, 'Schuhverwaltung - Neuen Schuh eingeben') %>
<%= render partial: 'shared/navigation', locals: {nav_runs: '', nav_shoes: 'active', nav_statistic: '', nav_about: '', nav_contact: ''} %>
<h3>Neuen Schuh eingeben</h3>
<%= render 'form' %>
<%= link_to 'Zurück', :back, :class => "speziell" %>