config/routes.rb
Laufverwaltung::Application.routes.draw do
  resources :shoes
  put "shoes/:id/hide" => "shoes#hide", as: 'hide_shoe'
  put "shoes" => "shoes#unhide", as: 'unhide_shoes'
	root to: 'pages#home'
	get "runs/statistic" => "runs#statistic", as: 'statistic'

  resources :runs
	resources :users, only: [:new, :create]

  post "runs/output" =>"runs#output", as: 'output'

	get "login" => "sessions#new", as: 'login'
	post "sessions" => "sessions#create", as: 'sessions'
	delete "logout" => "sessions#destroy", as: 'logout'

	get "pages/about" => "pages#about", as: 'about'
	get "pages/contact" => "pages#contact", as: 'contact'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RunBase | <%= yield(:title) %></title>
	<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/humanity/jquery-ui.css", "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<meta name="description" content=""/>
	<meta name="author" content=""/>
	<!-- mobile viewport optimisation -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- stylesheets -->
  <%= stylesheet_link_tag "css/central.css" %>
	<!--[if lte IE 7]>
	<%= stylesheet_link_tag "yaml/core/iehacks.min.css" %>
	<![endif]-->
	<!--[if lt IE 9]>
	 <%= stylesheet_link_tag "http://html5shim.googlecode.com/svn/trunk/html5.js" %>
	<![endif]-->
</head>

<body>
<header>
    <div class="ym-column">
    <div class="ym-col1">
    <div class="ym-cbox">
			<%= link_to image_tag("logo_2.png", :alt => "Logo"), runs_path %>
    </div>
    </div>
    <div class="ym-col3">
    <div class="ym-cbox">
			<%= yield(:navigation) %>
    </div>
    </div>
    </div>
</header>

    <div class="ym-grid">
	    <div class="ym-g80 ym-gl">
		    <div class="ym-gbox">
					<%= yield %>
		    </div>
	    </div>
    <div class="ym-g20 ym-gr">
	    <div class="ym-gbox">
				<%= image_tag("skyscraper120x600.jpg", :alt => "Werbung") %>
	    </div>
    </div>
   </div>

</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RunBase | <%= yield(:title) %></title>
	<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/overcast/jquery-ui.css", "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<meta name="description" content=""/>
	<meta name="author" content=""/>
	<!-- mobile viewport optimisation -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- stylesheets -->
  <%= stylesheet_link_tag "css/central.css" %>
	<!--[if lte IE 7]>
	<%= stylesheet_link_tag "yaml/core/iehacks.min.css" %>
	<![endif]-->
	<!--[if lt IE 9]>
	 <%= stylesheet_link_tag "http://html5shim.googlecode.com/svn/trunk/html5.js" %>
	<![endif]-->
</head>

<body>
			<%= image_tag("logo_2.png", :alt => "Logo", :class => "logo") %>
			<%= image_tag("background.jpg", :alt => "Hintergrund", :class => "bg") %>
			<%= yield %>
</body>
</html>